# Generated by Django 3.2.6 on 2021-08-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveBigIntegerField(null=True, unique=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('link', models.URLField(max_length=300, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
