# Generated by Django 3.2.6 on 2021-08-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='index',
        ),
    ]
